######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 24 17:27:22 2012
######################################################################

TEMPLATE = app
TARGET = ../../bin/QtLatency

DEPENDPATH += .

QMAKE_CXXFLAGS += -D_FORTIFY_SOURCE=0 -D_GNU_SOURCE -DULAPI -mhard-float -fno-fast-math -mieee-fp -fno-unsafe-math-optimizations -Wframe-larger-than=2560 -Os -std=c++0x
INCLUDEPATH += . /usr/include usr/include/linux /usr/local/include/machinekit /usr/local/include /opt/Qt/5.4/gcc/include /opt/Qt/5.4/gcc/include/QtDesigner
QMAKE_LIBDIR += /lib /usr/local/lib/machinekit /opt/Qt/5.4/gcc_64/plugins/designer
LIBS += -llinuxcncini -llinuxcnchal -lnml -llinuxcnc -lposemath -lhalwidgets_qt5 -lQtPanel

QT += core gui widgets

# Input
HEADERS += qtlatency.h
SOURCES += main.cpp qtlatency.cpp
