#!/bin/bash
set -e

if [ -n "$QTDIR" ] ; then
    echo "Using QTDIR found at $QTDIR"
else
    echo "################################################################"
    echo ""
    echo "No QTDIR set"
    echo ""
    echo "This branch requires Qt5 to be installed."
    echo ""    
    echo "Set env variable QTDIR to the root dir of your Qt5 installation,"
    echo "export QTDIR in your ~/.bashrc file, log out and log back in."
    echo ""
    echo "################################################################"
    exit 1
fi


OLDWD=$PWD
cd ../qt/QtChooser
qmake -makefile
make -j$(nproc);

cd ../QtAxis
qmake -makefile
make -j$(nproc);

cd ../QtXHCMonitor
qmake -makefile
make -j$(nproc);

cd ../QtPopImage
qmake -makefile
make -j$(nproc);

cd ../QtShowError
qmake -makefile
make -j$(nproc);

cd ../QtHalShow
qmake -makefile
make -j$(nproc);

cd ../QtVCP
qmake -makefile
make -j$(nproc);

cd $OLDWD

strip ../bin/QtChooser
strip ../bin/QtAxis
strip ../bin/QtXHCMonitor
strip ../bin/QtPopImage
strip ../bin/QtShowError
strip ../bin/QtHalShow
strip ../bin/QtVCP

echo "Qt programs built and installed"



